create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    ic_number text not null unique,
    full_name text not null,
    role text not null check (role in ('Executive', 'Lecturer')),
    pensyarah text,
    is_active boolean not null default true
);

create index if not exists app_users_ic_number_idx
on public.app_users (ic_number);

create index if not exists app_users_role_idx
on public.app_users (role);
