create table if not exists public.edit_history (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    source text not null default 'APP',
    user_id text,
    user_name text,
    user_role text,
    action text not null,
    dataset text not null,
    record_id text,
    details text,
    old_data jsonb,
    new_data jsonb
);

alter table public.edit_history
add column if not exists source text not null default 'APP';

alter table public.edit_history
add column if not exists old_data jsonb;

alter table public.edit_history
add column if not exists new_data jsonb;

create index if not exists edit_history_created_at_idx
on public.edit_history (created_at desc);

create index if not exists edit_history_source_idx
on public.edit_history (source);

create index if not exists edit_history_user_role_idx
on public.edit_history (user_role);

create index if not exists edit_history_dataset_idx
on public.edit_history (dataset);

create or replace function public.log_edit_history_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    affected_id text;
    actor_id text;
    actor_name text;
    actor_role text;
    old_row jsonb;
    new_row jsonb;
begin
    if tg_table_name = 'edit_history' then
        if tg_op = 'DELETE' then
            return old;
        end if;
        return new;
    end if;

    if tg_op = 'INSERT' then
        affected_id := to_jsonb(new)->>'id';
        old_row := null;
        new_row := to_jsonb(new);
    elsif tg_op = 'UPDATE' then
        affected_id := coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id');
        old_row := to_jsonb(old);
        new_row := to_jsonb(new);
    else
        affected_id := to_jsonb(old)->>'id';
        old_row := to_jsonb(old);
        new_row := null;
    end if;

    actor_id := nullif(current_setting('request.jwt.claim.sub', true), '');
    actor_name := coalesce(
        nullif(current_setting('request.jwt.claim.email', true), ''),
        nullif(current_setting('request.jwt.claim.role', true), ''),
        current_user
    );
    actor_role := coalesce(nullif(current_setting('request.jwt.claim.role', true), ''), current_user);

    insert into public.edit_history (
        source,
        user_id,
        user_name,
        user_role,
        action,
        dataset,
        record_id,
        details,
        old_data,
        new_data
    )
    values (
        'SUPABASE',
        actor_id,
        actor_name,
        actor_role,
        tg_op,
        tg_table_name,
        affected_id,
        concat(tg_op, ' on ', tg_table_name, ' through Supabase/database'),
        old_row,
        new_row
    );

    if tg_op = 'DELETE' then
        return old;
    end if;
    return new;
end;
$$;

drop trigger if exists students_edit_history_trigger on public.students;
create trigger students_edit_history_trigger
after insert or update or delete on public.students
for each row execute function public.log_edit_history_trigger();

drop trigger if exists lecturers_edit_history_trigger on public.lecturers;
create trigger lecturers_edit_history_trigger
after insert or update or delete on public.lecturers
for each row execute function public.log_edit_history_trigger();

drop trigger if exists programs_edit_history_trigger on public.programs;
create trigger programs_edit_history_trigger
after insert or update or delete on public.programs
for each row execute function public.log_edit_history_trigger();

drop trigger if exists results_edit_history_trigger on public.results;
create trigger results_edit_history_trigger
after insert or update or delete on public.results
for each row execute function public.log_edit_history_trigger();
