create table if not exists public.table_spm_cgpa (
    id bigint generated by default as identity primary key,
    spm text not null unique,
    cgpa numeric(3, 2) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.table_pspm_cgpa (
    id bigint generated by default as identity primary key,
    pspm text not null unique,
    cgpa numeric(3, 2) not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into public.table_spm_cgpa (spm, cgpa)
values
    ('A+', 4.00),
    ('A', 3.67),
    ('A-', 3.33),
    ('B+', 3.00),
    ('B', 2.67),
    ('C+', 2.33),
    ('C', 2.00),
    ('D', 1.67),
    ('E', 1.33),
    ('G', 0.00)
on conflict (spm)
do update set
    cgpa = excluded.cgpa,
    updated_at = now();

insert into public.table_pspm_cgpa (pspm, cgpa)
values
    ('A', 4.00),
    ('A-', 3.67),
    ('B+', 3.33),
    ('B', 3.00),
    ('B-', 2.67),
    ('C+', 2.33),
    ('C', 2.00),
    ('C-', 1.67),
    ('D+', 1.33),
    ('F', 0.00)
on conflict (pspm)
do update set
    cgpa = excluded.cgpa,
    updated_at = now();
